setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('apps.estoque.urls')),
        path('', include('apps.usuario.urls')),
        path('', include('apps.carrinho.urls')),
        path('', include('apps.requisition.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/estoque/models.py
from django.db import models

class Material(models.Model):
    OPCOES_CATEGORIA = [
        ("MAT-TIC", "Material de TIC"),
        ("MAT-EXPEDIENTE", "Material de Expediente"),
        ("MAT-ESCRITORIO", "Material de Escritório"),
    ]

    OPCOES_MEDIDA = [
        ("UND", "Unidade"),
        ("KG", "Quilograma"),
        ("PCT", "Pacote"),
    ]

    desc = models.CharField(max_length=100, null=False, blank=False)
    categoria = models.CharField(max_length=100, choices=OPCOES_CATEGORIA, default="")
    qtd = models.IntegerField( null=False, blank=False)
    tipo = models.CharField(max_length=100, choices=OPCOES_MEDIDA, default="UND")
    foto = models.ImageField(upload_to="fotos/%Y/%m/%d/", blank=True)

    def __str__(self):
        return self.desc

templates/partials/alertas.html
{% if messages %}
    <div class="container-sm mb-1">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{message}}
        </div>
        {% endfor %}
    </div>    
{% endif %}

templates/partials/footer.html
{% load static %}
<footer>
    <div class="container mt-5">
        <p class="text-end">
            <a class="text-decoration-none" href="https://www.threads.net/@vaniloalexandre" target=”_blank”>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-threads" viewBox="0 0 16 16">
                    <path d="M6.321 6.016c-.27-.18-1.166-.802-1.166-.802.756-1.081 1.753-1.502 3.132-1.502.975 0 1.803.327 2.394.948s.928 1.509 1.005 2.644q.492.207.905.484c1.109.745 1.719 1.86 1.719 3.137 0 2.716-2.226 5.075-6.256 5.075C4.594 16 1 13.987 1 7.994 1 2.034 4.482 0 8.044 0 9.69 0 13.55.243 15 5.036l-1.36.353C12.516 1.974 10.163 1.43 8.006 1.43c-3.565 0-5.582 2.171-5.582 6.79 0 4.143 2.254 6.343 5.63 6.343 2.777 0 4.847-1.443 4.847-3.556 0-1.438-1.208-2.127-1.27-2.127-.236 1.234-.868 3.31-3.644 3.31-1.618 0-3.013-1.118-3.013-2.582 0-2.09 1.984-2.847 3.55-2.847.586 0 1.294.04 1.663.114 0-.637-.54-1.728-1.9-1.728-1.25 0-1.566.405-1.967.868ZM8.716 8.19c-2.04 0-2.304.87-2.304 1.416 0 .878 1.043 1.168 1.6 1.168 1.02 0 2.067-.282 2.232-2.423a6.2 6.2 0 0 0-1.528-.161"/>
                </svg>
            </a>
            <a class="text-decoration-none" href="https://github.com/Maygriev" target=”_blank”>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                    <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
                </svg>
            </a>
            Desenvolvido por Vanilo Alexandre
        </p>
    </div>
</footer>

templates/partials/header.html
{% load static %}
<header>
    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-sm-auto">
                <a class="text-decoration-none" href="{% url 'home'%}">
                    <img src="{% static '/assets/images/logo-sigal.svg' %}" style="max-height: 60px; max-width: 60px;">
                </a>
            </div>
            <div class="col">
                <span class="fs-5 fw-bold">SIGAL<br/></span>
                <span class="fs-6">Sistema de Gestão de Almoxarifado</span>
            </div>
            {# Sessão do template dedicada a exibir o botão de Carrinho e Logout #}
            {# Verifica se existe um usuário logado#}
            {% if user.is_authenticated %}
                <div class="col text-end align-self-center">
                    <a class="btn position-relative" href="{% url 'detail-carrinho'%}" role="button">
                        <img style="max-width: 32px; max-height: 32px;" src="{% static '/assets/images/cart.svg' %}" alt="carrinho">
                        {# Verifica se existe algum item no carrinho para exibir o contador #}
                        {% if request.COOKIES.totalCarrinho %}
                            <span class="position-absolute top-100 start-0 translate-middle p-2 badge rounded-pill bg-info">
                                {# Atualiza com a quantidade de itens no carrinho #}
                                {{request.COOKIES.totalCarrinho}}<span class="visually-hidden">Itens no Carrinho</span>
                            </span>
                        {% endif %}
                    </a>
                    <a class="btn btn-danger" href="{% url 'logout'%}" role="button">Logout</a>
                </div>
            {% endif %}
        </div>
    </div>
</header>

templates/partials/materialActions.html
{% load static %}
{% if cards %}
{% for material in cards %}
<tr>
    <th scope="row">{{material.id}}</th>
    <td>{{material.desc}}</td>
    <td>{{material.qtd}}</td>
    <td>{{material.tipo}}</td>
    {% if material.foto == "" or material.foto == null %}
        <td><img class="img-thumbnail" style="max-width: 64px; max-height: 64px;" src="{% static '/assets/images/not-found.svg' %}" alt="foto"></td>
    {% else %}
        <td><img class="img-thumbnail" style="max-width: 64px; max-height: 64px;" src="{{ material.foto.url }}" alt="foto"></td>
    {% endif %}
    <td>
        <a class="btn btn-dark" href="{% url 'view-material' material.id %}" role="button">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
            </svg>
        </a>
        <a class="btn btn-dark" href="#" role="button">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus-fill" viewBox="0 0 16 16">
                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0M9 5.5V7h1.5a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0V8H6.5a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 1 0"/>
            </svg>
        </a>
        <a class="btn btn-dark" href="#" role="button">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-dash-fill" viewBox="0 0 16 16">
                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0M6.5 7h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1 0-1"/>
            </svg>
        </a>
        {% if perms.estoque.change_material %}
            <a class="btn btn-dark" href="{% url 'edit-material' material.id %}" role="button">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                </svg>
            </a>
        {% endif %}
    </td>
</tr>
{% endfor%}
{% else %}
{% endif %}

templates/partials/navbar.html
{% if user.is_authenticated %}
<nav class="navbar sticky-top navbar-dark bg-dark container-sm mb-3">
    <div class="container-fluid justify-content-start">
        <a href="{% url 'home'%}" class="navbar-brand">Home</a>
        <div class="navbar-nav flex-row">
            <a href="{% url 'list-material'%}" class="nav-link p-2">Estoque</a>
            <a href="{% url 'my-requisitions'%}" class="nav-link p-2">Requisições</a>
        </div>
    </div>
</nav>
{% endif %}