apps/requisition/urls.py
from django.urls import path
from apps.requisition.views import viewRequisition, myRequisitions, addRequisition

urlpatterns = [
    path("my-requisitions", myRequisitions, name="my-requisitions"),
    path("checkout", addRequisition, name="checkout"),
    path("view-requisition/<int:reqID>/", viewRequisition, name="view-requisition"),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('apps.estoque.urls')),
        path('', include('apps.usuario.urls')),
        path('', include('apps.carrinho.urls')),
        path('', include('apps.requisition.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/requisition/models.py
from django.db import models

from datetime import datetime
from django.contrib.auth.models import User
from apps.estoque.models import Material

class Requisition(models.Model):
    OPCOES_STATUS = [
        ("PENDENTE", "Pendente"),
        ("APROVADA", "Aprovada"),
        ("CANCELADA", "Cancelada"),
        ("REPROVADA", "Reprovada"),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(Material, through="RequisitionItem")
    status = models.CharField(max_length=100, choices=OPCOES_STATUS, default="PENDENTE")
    dateReq = models.DateTimeField(default=datetime.now, blank=False)

    def __str__(self):
        return f"Requisição #{self.id}"
    
class RequisitionItem(models.Model):
    itemReq = models.ForeignKey(Requisition, on_delete=models.CASCADE)
    itemMat = models.ForeignKey(Material, on_delete=models.CASCADE)
    itemQtd = models.IntegerField(null=False, blank=False)

    def __str__(self) -> str:
        return f"{self.itemQtd} x {self.itemMat.desc}"

apps/requisition/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib import messages
from django.core.paginator import Paginator

from apps.carrinho.models import Carrinho
from apps.requisition.models import Requisition, RequisitionItem

def viewRequisition(request, reqID):
    if not request.user.is_authenticated:
        messages.error(request, 'Usuário não logado')
        return redirect('login')
    
    req = get_object_or_404(Requisition, id=reqID)
        
    return render(request, 'requisition/viewRequisition.html', {'req':req})

def addRequisition(request):
    if not request.user.is_authenticated:
        messages.error(request, 'Usuário não logado')
        return redirect('login')
    
    carrinho = Carrinho.objects.filter(user=request.user)

    req = Requisition.objects.create(user=request.user)

    for itemCart in carrinho:
        reqItem = RequisitionItem.objects.create(itemReq=req, itemMat=itemCart.item, itemQtd=itemCart.qtd)
        reqItem.save()
        itemCart.delete()

    req.save()

    messages.success(request, 'Requisição enviada com sucesso')

    response = redirect("my-requisitions")
    response.delete_cookie("totalCarrinho")

    return response

def myRequisitions(request):
    if not request.user.is_authenticated:
        messages.error(request, 'Usuário não logado')
        return redirect('login')
    
    items = Requisition.objects.filter(user=request.user).order_by("-dateReq")
    items = Paginator(items, 10)
    page_number = request.GET.get("page")
    page_obj = items.get_page(page_number)
    
    return render(request, 'requisition/myRequisition.html', {"cards": page_obj})

templates/requisition/myRequisition.html
{% extends 'shared/base.html' %}
{% load static %}

{% block title %}
 - Minhas Requisições
{% endblock %}

{% block content %}
<body>
    <div class="container-sm mt-3">
        <div>
            <form class="row row-cols-lg-auto g-3" action="{% url 'home' %}" method="get">
                <div class="col-12">
                    <input name="q" class="form-control" type="text" placeholder="Digite sua busca...">
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-dark">Buscar</button>
                </div>
            </form>
        </div>
        {% include 'requisition/requisitionTable.html' %}
        <nav aria-label="Paginação da Lista de Materiais">
            <ul class="pagination">
                {% if cards.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">Primeira</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ cards.previous_page_number }}">{{ cards.previous_page_number }}</a>
                    </li>
                {% endif %}

                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ cards.number }}</a>
                </li>
                
                {% if cards.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ cards.next_page_number }}">{{ cards.next_page_number }}</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ cards.paginator.num_pages }}">Ultima</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</body>
{% endblock %}

templates/requisition/requisitionTable.html
{% load static %}
<table class="table table-striped align-middle">
    <thead>
        <tr class="text-center">
            <th scope="col">ID</th>
            <th scope="col">Envio</th>
            <th scope="col">Items</th>
            <th scope="col">Status</th>
            <th scope="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        {% if cards %}
        {% for item in cards %}
        <tr class="text-center">
            <td>{{item.id}}</td>
            <td>{{item.dateReq|date:'d/m/Y - H:i'}}</td>
            <td>
                {% for material in item.requisitionitem_set.all %}
                <div class="row row-cols-auto">
                    {% if material.itemMat.foto == "" or material.itemMat.foto == null %}
                        <img class="img-thumbnail" style="max-width: 64px; max-height: 64px;" src="{% static '/assets/images/not-found.svg' %}" alt="foto">
                    {% else %}
                        <img class="img-thumbnail" style="max-width: 64px; max-height: 64px;" src="{{ material.itemMat.foto.url }}" alt="foto">
                    {% endif %}
                    <p class="text-start text-wrap">
                        {{material}}
                    </p>
                </div>
                {% endfor%}
            </td>
            <td>{{item.status}}</td>
            <td>
                <a class="btn btn-dark" href="{% url 'view-requisition' item.id %}" role="button">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                    </svg>
                </a>
                {% if perms.requisition.change_requisition %}
                    <a class="btn btn-dark" href="{% url 'home' %}" role="button">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
                        </svg>
                    </a>
                {% endif %}
            </td>
        </tr>
        {% endfor%}
        {% else %}
        {% endif %}
    </tbody>
</table>

templates/requisition/viewRequisition.html
{% extends 'shared/base.html' %}
{% load static %}

{% block title %}
 - Detalhar Requisição
{% endblock %}

{% block content %}
<body>
    <div class="container-sm">
        {% if req %}
            <div class="d-flex flex-row mb-3 justify-content-center">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Requisição #{{req.id}}</li>
                    <li class="list-group-item">Enviado: {{req.dateReq|date:'d/m/Y - H:i'}}</li>
                    <li class="list-group-item">
                        Material Solicitado:
                        <ul class="list-group">
                            {% for material in req.requisitionitem_set.all %}
                                <li class="list-group-item">
                                    {% if material.itemMat.foto == "" or material.itemMat.foto == null %}
                                        <img class="img-thumbnail" style="max-width: 64px; max-height: 64px;" src="{% static '/assets/images/not-found.svg' %}" alt="foto">
                                    {% else %}
                                        <img class="img-thumbnail" style="max-width: 64px; max-height: 64px;" src="{{ material.itemMat.foto.url }}" alt="foto">
                                    {% endif %}
                                    {{material}}
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            </div>
        {% else %}
            <h1>Requisição Inexistente</h1>
        {% endif%}
    </div>
</body>
{% endblock %}